apiVersion: v1
kind: Service
metadata:
  name: nsq
  labels:
    app: nsq
spec:
  ports:
  - port: 4150
    name: tcp
    targetPort: 4150
  - port: 4151
    name: http
    targetPort: 4151
  selector:
    app: nsq
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: nsq
  name: nsq
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nsq
  template:
    metadata:
      labels:
        app: nsq
    spec:
      containers:
        - name: nsq
          image: nsqio/nsq
          command:
            - /nsqd
          ports:
          - containerPort: 4150
            name: tcp
            protocol: TCP
          - containerPort: 4150
            name: http
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: data
        - name: nsqlookup
          image: nsqio/nsq
          command:
            - /nsqlookupd
          ports:
          - containerPort: 4160
            name: tcp
            protocol: TCP
          - containerPort: 4160
            name: http
            protocol: TCP
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookup
  labels:
    app: nsqlookup
spec:
  ports:
    - port: 4160
      name: tcp
      targetPort: 4160
    - port: 4161
      name: http
      targetPort: 4161
  selector:
    app: nsqlookup
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: nsqlookup
  labels:
    app: nsqlookup
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nsqlookup
  template:
    metadata:
      labels:
        app: nsqlookup
    spec:
      containers:
        - name: nsqlookup
          image: nsqio/nsq
          command:
            - /nsqlookupd
          ports:
            - containerPort: 4160
              name: tcp
              protocol: TCP
            - containerPort: 4160
              name: http
              protocol: TCP
